id: I3AAFC683
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:09:20+00:00'
last_modified: '2022-06-08T01:31:24.071962+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137863
  title: སྙན་ངག་མེ་ལོང་དང་བོད་མཁས་པའི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A1C8:
      image_group_id: I2PD19650
      title: ''
      total_pages: 514
      order: 1
      base_file: A1C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
